#!/usr/bin/env bash
# sources your virtualenv, and runs spy
# symlink to this file from your a directory in your PATH (I use ~/bin)

# get current directory, from http://stackoverflow.com/a/246128/398212
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source "$DIR/venv/bin/activate"
"$DIR/spy" "$@"
